language: php

addons:
 ssh_known_hosts:
  - whirlpool.obscure.systems

before_install:
  - openssl aes-256-cbc -K $encrypted_0ff6502eb394_key -iv $encrypted_0ff6502eb394_iv
  -in .travis/whirlpool.rsa.enc -out whirlpool.rsa -d

script: true

after_success:
  - chmod 600 whirlpool.rsa # this key should have push access
  - ssh-add whirlpool.rsa
  - git remote add deploy gitdeploy@whirlpool.obscure.systems:/var/git/wizards
  - git push deploy
